### ISSUE TITLE
Sample code fails with AttributeError: 'AlationDataQuality' object has no attribute

### ISSUE THREAD

**Issue by james-mesney** [Alation/Allie-SDK#15]
HI. The sample code at https://alation.github.io/Allie-SDK/ might have a problem.  Error is:

```
Traceback (most recent call last):
  File "/Users/james.mesney/Documents/code/allie-sdk/main.py", line 12, in <module>
    dq_fields = alation.data_quality.get_data_quality_rules()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AlationDataQuality' object has no attribute 'get_data_quality_rules'. Did you mean: 'get_data_quality_values'?
```

I have a valid refresh token and an access token is printed ok (line #9). 
Thanks
James

**Comment by marioaburto-alation** [comment]
Hi @james-mesney , thank you for bringing this up to our attention. This was fixed yesterday 7/2 on this pull request (https://github.com/Alation/Allie-SDK/pull/14). Docs have been updated along with the sample code, please pull the latest code. I'll close this issue for now but feel free to let us know if you see something that is not right.
