### ISSUE TITLE
Sample fails with AttributeError: 'NoneType' object has no attribute 'token_status'

### ISSUE THREAD

**Issue by james-mesney** [Alation/Allie-SDK#16]
I had another run with the (latest) Allie SDK and the sample code for getting data health rules. It fails with a different error:

```
(venv) james.mesney@james-mesney-RFG6NCQPG3 Allie-SDK % /Users/james.mesney/Documents/code/Allie-SDK/venv/bin/python /Users/james.mesn
ey/Documents/code/Allie-SDK/datahealthrules.py
ERROR MESSAGE: Error submitting the POST Request to: /integration/v1/validateRefreshToken/
ERROR CODE: 401000
ERROR DETAIL: Refresh token provided is expired or revoked.
Traceback (most recent call last):
  File "/Users/james.mesney/Documents/code/Allie-SDK/datahealthrules.py", line 3, in <module>
    alation = allie.Alation(
              ^^^^^^^^^^^^^^
  File "/Users/james.mesney/Documents/code/Allie-SDK/allie_sdk/alation.py", line 72, in __init__
    self.access_token = self.authentication.create_access_token().api_access_token
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james.mesney/Documents/code/Allie-SDK/allie_sdk/methods/authentication.py", line 55, in create_access_token
    if refresh_status.token_status.upper() != 'ACTIVE':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'token_status'
(venv) james.mesney@james-mesney-RFG6NCQPG3 Allie-SDK % 
```
The refresh token I'm using is active and good until Aug 30. Any idea what causes the  **_AttributeError: 'NoneType' object has no attribute 'token_status'_**? 

Thanks.

**Comment by james-mesney** [comment]
Update: In desperation, I generated another, new refresh token and this code is now working!  I don't know why the original token doesn't work.  

(The _AttributeError_ error message does not help one identify the problem)

**Comment by marioaburto-alation** [comment]
hi @james-mesney , glad that it is working for you now and thank you for your feedback. We are going to work on adding a better error message for when the refresh token is not valid.

**Comment by marioaburto-alation** [comment]
Commit https://github.com/Alation/Allie-SDK/pull/37 solves this issue. Closing this issue.
