### ISSUE TITLE
view_sql param passed validation but is not visible on Alation's related item

### ISSUE THREAD

**Issue by laskmat** [Alation/Allie-SDK#17]
hi,
I am wonder if that's issue with REST API or something connected. 
Tested on my trial account and my developer instance.
Example for trial acc:

`ss = AlationVirtualDataSource(
    access_token='<token>', session=requests.session(), host='https://<instance_id>.alationcloud.com'
)

vds_id = 1
view = VirtualDataSourceView()
view.key = '1.DEMO_SAMPLE_DATA.STRM_ANLYTCS_DM.CUSTOMER_VW'
view.table_comment = 'Testing View-Table'
view.view_sql = 'select * from TestTable1'
items = [view]
async_result = ss.post_metadata(ds_id=vds_id, vds_objects=items)
`

so the result is partially as expected: 
![image](https://github.com/user-attachments/assets/0b9ac632-0552-4ab7-a670-cf1709486a02)

CUSTOMER_VW was updated with new table_comment but **SQL** has gone! I mean - trial has sql DDLs added for views but for some reason when I'm trying to update this field with API (even with normal POST outside this lib), something breaks without any detailed info why.
But maybe I've missed something?

**Comment by marioaburto-alation** [comment]
Hi @laskmat, thank you for bringing this up to us. We are going to test this internally and will get back to you shortly with our findings.

**Comment by ignaszewskir** [comment]
Hi @laskmat I am not able to reproduce this in-house using your code. My view gets updated with the correct Source Comments as well as the SQL portion. Are you updating a Virtual Data Source View or Standard Data Source?

**Comment by laskmat** [comment]
@ignaszewskir seems that's Virtual Data Source View.

**Comment by laskmat** [comment]
hey @ignaszewskir @marioaburto-alation  seems that methods related to RDBMS works for updating VirtualDataSourceView. But is it right way to use that this way?
Could you please add some examples to SDK?

**Comment by ignaszewskir** [comment]
Hi @laskmat. The RDBMS API is meant for RMDBS data sources, and the Virtual Data Source API for Virtual data sources only.

**Comment by laskmat** [comment]
@ignaszewskir I guess we can close this issue for now - seems that each case should be checked with picking the best solution (and API's object).
Thanks
