### ISSUE TITLE
Validate token methods should not require authentication

### ISSUE THREAD

**Issue by marioaburto-alation** [Alation/Allie-SDK#34]
Methods `validate_refresh_token()` and `validate_access_token()` should not require the user to pass in a refresh token in order to instantiate the Alation class since these endpoints do not require an access token in the header. Users should be able to call on these methods without first authenticating into Alation.

**Comment by laskmat** [comment]
@marioaburto-alation does changing validate_ssl in Alation class takes part in calling this endpoint? Cuz I've found that when using poetry it doesnt works (but maybe it's poetry fault?)

**Comment by marioaburto-alation** [comment]
hi @laskmat , updating `validate_ssl` with the path to a valid cert should work and will take part when calling these endpoints, as well of the rest of the endpoints. I have not tried using poetry in the past so I can't say if poetry affects this functionality or not but we have tested passing in a path to a valid cert and it does work. I will be closing this issue but feel free to create another GitHub issue if you are having issues with the cert.

**Comment by marioaburto-alation** [comment]
Commit https://github.com/Alation/Allie-SDK/pull/37 solves this issue. Please refer to the updated docs: https://alation.github.io/Allie-SDK/pages/Authenticate.html#initialize-alation-without-auth-tokens

**Comment by marioaburto-alation** [comment]
see comment above.
