### ISSUE TITLE
Idea - Use automated framework for generating project base 

### ISSUE THREAD

**Issue by marsvack** [Alation/Allie-SDK#7]
Just want to say it’s awesome this project is being put together and think it will be great for Alation customers.  One major challenge I see with a project like this is long term maintainability as the API changes.  The need to manually maintain models and request/response payloads as the API changes will be added work.

One idea to help with this is leveraging something like this project - [OpenAPI-Python-Client](https://github.com/openapi-generators/openapi-python-client).  This takes in openapi configs (an index of Alation configs is [here](https://developer.alation.com/dev/docs/open-api-index)) and auto generates models, payloads, and classes for functionality.  Not everything generated would need to be used, you could take only what would be helpful as a base for whatever patterns are decided for the project.  Anyways, just wanted to start a discussion on it and would be happy to help contribute.

**Comment by marioaburto-alation** [comment]
Hi @marsvack, thank you for the feedback! We appreciate you taking a look at our project. We are currently reviewing frameworks, we will look into it and make a decision based on our findings.
